version: '3'

services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - 80:8080
    volumes:
      - type: bind
        source: "./frontend"
        target: "/app"
    entrypoint: "/bin/sh -c 'npm install && npm run start'"
    
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: "./backend"
        target: "/app"
    entrypoint: "/bin/sh -c 'python3 main.py'"
